[profile.release]
panic = 'unwind'

[workspace]
members = [
    'pallets/*',
    'traits/*',
    'node',
    'runtime/pioneer',
    'runtime/metaverse',
    'primitives/metaverse',
]
exclude = [
    '/dapps/luckydraw',
    '/dapps/airdrop',
    '/dapps/countrytoken',
    'pallets/oracle',
    'pallet/evm',
    'pallet/evm/*',
    'primitives/evm/',
    'modules/chainsafe',
    'runtime/tewai',
]

[patch.crates-io]
ethereum = { git = "https://github.com/AstarNetwork/ethereum", branch = "polkadot-v0.9.16" }
evm = { git = "https://github.com/AstarNetwork/evm", branch = "polkadot-v0.9.16" }
evm-gasometer = { git = "https://github.com/AstarNetwork/evm", branch = "polkadot-v0.9.16" }
evm-runtime = { git = "https://github.com/AstarNetwork/evm", branch = "polkadot-v0.9.16" }